### ISSUE TITLE
Improve worker protocol

### ISSUE THREAD

**Issue by abingham** [sixty-north/cosmic-ray#114]
We need to sharpen up the protocol for workers. Right now, for example, they don't behave well when they fail internally. We need to think hard about what they can report back, how they report it, etc...right now it's a bit _ad hoc_.

**Comment by abingham** [comment]
One example of bad behavior is here:
```
[2015-12-26 16:47:29,478: INFO/MainProcess] Received task: cosmic_ray.worker[2b6f0b4c-0f83-4024-90e1-44d7af08a17b]
[2015-12-26 16:48:04,075: ERROR/MainProcess] Task cosmic_ray.worker[2b6f0b4c-0f83-4024-90e1-44d7af08a17b] raised unexpected: JSONDecodeError('Expecting value: line 1 column 1 (char 0)',)
Traceback (most recent call last):
  File "/Users/sixtynorth/.virtualenvs/segpy/lib/python3.5/site-packages/celery-3.1.19-py3.5.egg/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/Users/sixtynorth/.virtualenvs/segpy/lib/python3.5/site-packages/celery-3.1.19-py3.5.egg/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/Users/sixtynorth/projects/sixty-north/cosmic-ray/cosmic_ray/worker.py", line 35, in worker_task
    result = json.loads(proc.stdout)
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by npandita19** [comment]
@abingham When can one expect this issue to be fixed? Is there a workaround for this bug?

**Comment by abingham** [comment]
This issues isn't a single bug *per se*, so there isn't a work around. Are you experiencing a specific bug?

As for when I'll get to work on this, that's hard to say.

**Comment by npandita19** [comment]
@abingham Cosmic-ray crashed on first attempt itself, so not sure what you are looking for. These are the steps I followed. 
$cosmic-ray init --timeout=10 AST_test_session astmonkey astmonkey/tests/
$cosmic-ray exec AST_test_session
--ABOVE CRASH--

Any leads on how can I bypass this would be helpful. Or if you can share few open source projects on which cosmic-ray works would be helpful too.

**Comment by abingham** [comment]
Would you mind opening a new issue for your particular crash? That way I can address any specific issues you're running into separately from this issue. 

As for open-source projects where this is known to work, the place to start is with the `test_project` directory in CR itself. You could also look at [segpy](https://github.com/sixty-north/segpy) where I know it's been used in the past. Thanks for your time on this; hopefully I'll be able to get you sorted out soon!
