### ISSUE TITLE
Bad failure mode when worker can't import module

### ISSUE THREAD

**Issue by abingham** [sixty-north/cosmic-ray#161]
We don't get very feedback when the celery worker process is unable to import the module under test. 

The worker does something like this:

```
Traceback (most recent call last):
  File "/home/austin/.virtualenvs/cosmic-ray/lib/python3.4/site-packages/cosmic_ray-1.0.0a0-py3.4.egg/cosmic_ray/worker.py", line 64, in worker
    module = importlib.import_module(module_name)
  File "/home/austin/.virtualenvs/cosmic-ray/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2224, in _find_and_load_unlocked
ImportError: No module named 'adam'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/austin/.virtualenvs/cosmic-ray/bin/cosmic-ray", line 9, in <module>
    load_entry_point('cosmic-ray==1.0.0a0', 'console_scripts', 'cosmic-ray')()
  File "/home/austin/.virtualenvs/cosmic-ray/lib/python3.4/site-packages/cosmic_ray-1.0.0a0-py3.4.egg/cosmic_ray/cli.py", line 365, in main
    sys.exit(handler(sub_config))
  File "/home/austin/.virtualenvs/cosmic-ray/lib/python3.4/site-packages/cosmic_ray-1.0.0a0-py3.4.egg/cosmic_ray/cli.py", line 300, in handle_worker
    test_runner)
  File "/home/austin/.virtualenvs/cosmic-ray/lib/python3.4/site-packages/cosmic_ray-1.0.0a0-py3.4.egg/cosmic_ray/worker.py", line 103, in worker
    res.extend(module_diff)
UnboundLocalError: local variable 'module_diff' referenced before assignment
[2016-07-25 06:19:36,553: ERROR/PoolWorker-1] Task cosmic_ray.tasks.worker[e0f531ef-5cd0-442c-8665-e1110ba0421a] raised unexpected: ValueError('Expecting value: line 1 column 1 (char 0)',)
Traceback (most recent call last):
  File "/home/austin/.virtualenvs/cosmic-ray/lib/python3.4/site-packages/celery-4.0.0rc3-py3.4.egg/celery/app/trace.py", line 358, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/austin/.virtualenvs/cosmic-ray/lib/python3.4/site-packages/celery-4.0.0rc3-py3.4.egg/celery/app/trace.py", line 609, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/austin/src/cosmic-ray/cosmic_ray/tasks/worker.py", line 51, in worker_task
    result = json.loads(outs)
  File "/usr/lib/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.4/json/decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)
```

and the client does something like this:

```
(cosmic-ray)austin@cosmic-ray-dev:~/src/cosmic-ray/test_project$ cosmic-ray load cosmic-ray.pytest.conf 
INFO:root:timeout = 4.65264 seconds
INFO:root:Modules discovered: ['adam']
Traceback (most recent call last):
  File "/home/austin/.virtualenvs/cosmic-ray/bin/cosmic-ray", line 9, in <module>
    load_entry_point('cosmic-ray==1.0.0a0', 'console_scripts', 'cosmic-ray')()
  File "/home/austin/.virtualenvs/cosmic-ray/lib/python3.4/site-packages/cosmic_ray-1.0.0a0-py3.4.egg/cosmic_ray/cli.py", line 365, in main
    sys.exit(handler(sub_config))
  File "/home/austin/.virtualenvs/cosmic-ray/lib/python3.4/site-packages/cosmic_ray-1.0.0a0-py3.4.egg/cosmic_ray/cli.py", line 79, in handle_load
    return main(argv=list(argv))
  File "/home/austin/.virtualenvs/cosmic-ray/lib/python3.4/site-packages/cosmic_ray-1.0.0a0-py3.4.egg/cosmic_ray/cli.py", line 365, in main
    sys.exit(handler(sub_config))
  File "/home/austin/.virtualenvs/cosmic-ray/lib/python3.4/site-packages/cosmic_ray-1.0.0a0-py3.4.egg/cosmic_ray/cli.py", line 191, in handle_run
    handle_exec(configuration)
  File "/home/austin/.virtualenvs/cosmic-ray/lib/python3.4/site-packages/cosmic_ray-1.0.0a0-py3.4.egg/cosmic_ray/cli.py", line 171, in handle_exec
    cosmic_ray.commands.execute(db)
  File "/home/austin/.virtualenvs/cosmic-ray/lib/python3.4/site-packages/cosmic_ray-1.0.0a0-py3.4.egg/cosmic_ray/commands/execute.py", line 21, in execute
    job_id, command, (result_type, result_data) = r.get()
  File "/home/austin/.virtualenvs/cosmic-ray/lib/python3.4/site-packages/celery-4.0.0rc3-py3.4.egg/celery/result.py", line 192, in get
    callback=callback,
  File "/home/austin/.virtualenvs/cosmic-ray/lib/python3.4/site-packages/celery-4.0.0rc3-py3.4.egg/celery/backends/async.py", line 170, in wait_for_pending
    return result.maybe_throw(callback=callback, propagate=propagate)
  File "/home/austin/.virtualenvs/cosmic-ray/lib/python3.4/site-packages/celery-4.0.0rc3-py3.4.egg/celery/result.py", line 294, in maybe_throw
    self.throw(value, self._to_remote_traceback(tb))
  File "/home/austin/.virtualenvs/cosmic-ray/lib/python3.4/site-packages/celery-4.0.0rc3-py3.4.egg/celery/result.py", line 287, in throw
    self.on_ready.throw(*args, **kwargs)
  File "/home/austin/.virtualenvs/cosmic-ray/lib/python3.4/site-packages/vine-1.1.1-py3.4.egg/vine/promises.py", line 205, in throw
    reraise(type(exc), exc, tb)
  File "/home/austin/.virtualenvs/cosmic-ray/lib/python3.4/site-packages/vine-1.1.1-py3.4.egg/vine/five.py", line 173, in reraise
    raise value
celery.backends.base.ValueError: Expecting value: line 1 column 1 (char 0)
```

So something in the worker subprocess is producing non-JSON outout that the celery worker doesn't like, and this results in the client barfing. Shouldn't be too hard to sort out.

**Comment by abingham** [comment]
An easy way to replicate this is with the adam tests. Start the celery worker in some directory other than `test_project`, and then run one of the tests. You'll see this failure.
