### ISSUE TITLE
Quickstart instructions seem broken

### ISSUE THREAD

**Issue by boxed** [sixty-north/cosmic-ray#164]
Did pip install cosmic_ray, worked fine. Installed celery and rabbitmq. Then:

```
(venv3)➜ tri.declarative git:(master) ✗ celery -A cosmic_ray.tasks.worker worker
Traceback (most recent call last):
  File "/Users/boxed/Projects/tri.declarative/venv3/bin/celery", line 11, in <module>
    sys.exit(main())
  File "/Users/boxed/Projects/tri.declarative/venv3/lib/python3.5/site-packages/celery/__main__.py", line 30, in main
    main()
  File "/Users/boxed/Projects/tri.declarative/venv3/lib/python3.5/site-packages/celery/bin/celery.py", line 81, in main
    cmd.execute_from_commandline(argv)
  File "/Users/boxed/Projects/tri.declarative/venv3/lib/python3.5/site-packages/celery/bin/celery.py", line 793, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/Users/boxed/Projects/tri.declarative/venv3/lib/python3.5/site-packages/celery/bin/base.py", line 309, in execute_from_commandline
    argv = self.setup_app_from_commandline(argv)
  File "/Users/boxed/Projects/tri.declarative/venv3/lib/python3.5/site-packages/celery/bin/base.py", line 469, in setup_app_from_commandline
    self.app = self.find_app(app)
  File "/Users/boxed/Projects/tri.declarative/venv3/lib/python3.5/site-packages/celery/bin/base.py", line 489, in find_app
    return find_app(app, symbol_by_name=self.symbol_by_name)
  File "/Users/boxed/Projects/tri.declarative/venv3/lib/python3.5/site-packages/celery/app/utils.py", line 235, in find_app
    sym = symbol_by_name(app, imp=imp)
  File "/Users/boxed/Projects/tri.declarative/venv3/lib/python3.5/site-packages/celery/bin/base.py", line 492, in symbol_by_name
    return symbol_by_name(name, imp=imp)
  File "/Users/boxed/Projects/tri.declarative/venv3/lib/python3.5/site-packages/kombu/utils/__init__.py", line 96, in symbol_by_name
    module = imp(module_name, package=package, **kwargs)
  File "/Users/boxed/Projects/tri.declarative/venv3/lib/python3.5/site-packages/celery/utils/imports.py", line 101, in import_from_cwd
    return imp(module, package=package)
  File "/Users/boxed/Projects/tri.declarative/venv3/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'cosmic_ray.tasks'
```

😢 

installing from source seems to work better, maybe you need to publish a never version of cosmic ray to pypi?

**Comment by abingham** [comment]
Yeah, I probably need to push a new version. Sorry about that.

**Comment by abingham** [comment]
I've pushed up a new version. Try it out and let me know if you have any more problems.

**Comment by boxed** [comment]
I cloned the repo and did it that way. Seemed to work... except that it can't connect to rabbit and I don't understand why (using homebrew to install rabbit). Maybe it would be better if the default way of working out of the box didn't require so much setup? I just want to try it a bit on a very trivial little lib, so it's a pity that I have to wade through so much setup...

**Comment by abingham** [comment]
Yeah, it's a bit unwieldy for just taking it for a spin. I have ideas first
simpler task distribution backends, but not much time to devote to it

What problems are you seeing with celery? Is it the exec command that's
having trouble, or the workers?

**Comment by boxed** [comment]
[2016-08-06 14:48:56,113: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.

As for task distribution, why not just do py.test? It has built in support for that.

**Comment by abingham** [comment]
I wasn't aware of py.test's support for task distribution, but it's probably not a practical solution for cosmic ray. For one thing, we need the worker nodes to do mutation of code before running tests. Perhaps we could make py.test do that, but it doesn't seem likely to be a good fit. 

Another reason is that we want to be able to support arbitrary test systems, even those that py.test doesn't support. So again, while we might be able to convince py.test to do what we want, it feels a bit perverse.

Ultimately, it's a design choice to keep test running and task distribution separate. Py.test is good at running tests, and I'm willing to wager that celery is (much) better at the job of pure task distribution. I could be wrong, and I'm receptive to being shown so, but trying to use py.test for task distribution for CR feels a bit like a "golden hammer" solution.

**Comment by boxed** [comment]
> Another reason is that we want to be able to support arbitrary test systems

Yea ok, that'd be enough. Seems a pity to write your own task distribution system instead of spending that time on the mutation stuff.

> Ultimately, it's a design choice to keep test running and task distribution separate

Well... is it separate? How do I run the tests without the task distribution then? Because this is causing me lots of problems even before I can figure out of cosmic ray is even something I want to use.

**Comment by abingham** [comment]
>  Seems a pity to write your own task distribution system instead of spending that time on the mutation stuff.
All things considered, celery pretty much stayed out of my way and made the task distribution effort about as trivial as it could be. 

The issues you're seeing with rabbitmq on OSX are a bit frustrating, though. I'm not sure what's going on there. I did a full uninstall/reinstall of rabbitmq on el capitan, and I didn't experience any problems. It seems that you're [not the only one with issues](http://apple.stackexchange.com/questions/217203/rabbitmq-can-not-start-broker), though.

> Well...is it separate?
It is insofar as the task distribution system has zero dependencies on the test runner, and the test runner has zero dependencies on the task distribution system. The system as a whole needs both to work, so you're right in the sense that CR currently needs each to do its job. 

As I mentioned earlier, with infinite time and/or money I'd love to abstract the task distribution side of things so that you could have the choice of e.g. running everything locally and serially. In the end, though, distributed processing - or, more accurately, the possibility for massive parallelization - is so important for successful mutation testing in the real world that I have to prioritize it.
