### ISSUE TITLE
Make mutation generation and execution seperate? 

### ISSUE THREAD

**Issue by grapherd** [sixty-north/cosmic-ray#197]
As now `cosmic-ray` using occurrence to trigger source code mutation, and execution at the same time (in `worker.py`).

This lets the program can't using the plugin to change the strategy of how to mutate the code.

In [Overcoming the Equivalent Mutant Problem](http://madeyski.e-informatyka.pl/download/Madeyski13TSE.pdf), points out may have different algorithm to generate mutation, maybe we can consider separating generation and execution phase, then it will be more friendly to introduce different mutation algorithms.

**Comment by abingham** [comment]
This is an interesting topic! I'd like to read that paper and some of its
references in more detail, but it sounds like second-order mutation is
something we need to consider.

I think you're right that our current implementation might be too simple.
Perhaps we need a way to compose various types of processing to sit between
a) the unmutated AST and b) the execution of tests. We may even need to be
able to let one mutation run schedule more test runs.

**Comment by grapherd** [comment]
I think maybe occurrence need to change to mutant node and node occurance. Then we can generate mutant point, and pass to cerely.

Also, we can then generate higher order mutant, since now occurrence won't point out which operator we change it, so occurrence 0 and occurrence 1 may mutant at same operator.

If we change it, we can specific different node by:

    n = 1, occurrence = 2
    n = 2 , occurrence = 2

**Comment by abingham** [comment]
I don't know if I entirely understand what you're proposing (probably because I need to understand more about higher-order mutants). But it sounds like you're saying this: we need to stop passing occurrence to the workers, and instead we need to tell the worker which AST node to work on. Is that correct?

If so, then we face a bit of a design challenge. I'm not sure the best way to pass that kind of information over celery. That is, I don't think we can just pass a node reference over celery. We might, instead, need to find some way of sending the nodes "address" so that the worker can locate the node in the AST it generates. I can think of schemes for doing this, but I'd prefer to use an existing one if possible. Maybe astroid or some other project can help us here.

Anyhow, this is a very interesting topic, and I'm curious to see how it drives the design of CR. Thanks!

**Comment by grapherd** [comment]
@abingham Yep, the occurrence model can't tell which node we are mutant now. You can see this paper for some quick introduce << Problems of Mutation Testing and Higher Order Mutation Testing >>, fig3 gave some example about high order mutants:
![alt](http://i.imgur.com/Rt1fxDY.png)

I'm now trying to use exist model to generate high order mutants, you can reference [mut.py](https://bitbucket.org/khalas/mutpy) which allow high order mutants. Also I think mutpy output is more intuitive for user.

**Comment by grapherd** [comment]
You can try this [last2first example](https://github.com/grapherd/cosmic-ray/tree/last_to_first_example)

```sh
git clone https://github.com/grapherd/cosmic-ray/tree/last_to_first_example
git checkout last_to_first_example
cd last2first_example
cosmic-ray --verbose run --test-runner nose --baseline=100 example.json main.py -- tests.py
cosmic-ray report example.json --full-report
```

Output should like this
```sh
➜  test cosmic-ray report example.json --full-report                                               
job ID 1:Outcome.KILLED:main
command: cosmic-ray worker main ['number_replacer', 'add_not'] [2, 0] nose -- tests.py
Traceback (most recent call last):
  File "/tmp/test/tests.py", line 9, in test_10_should_return_5
    self.assertEqual(main.foo(10), 5)
AssertionError: 20 != 5

Traceback (most recent call last):
  File "/tmp/test/tests.py", line 12, in test_11_should_return_21
    self.assertEqual(main.foo(11), 21)
AssertionError: 5 != 21

Traceback (most recent call last):
  File "/tmp/test/tests.py", line 15, in test_9_should_return_4
    self.assertEqual(main.foo(9), 4)
AssertionError: 19 != 4

--- mutation diff ---
--- a/tmp/test/main.py
+++ b/tmp/test/main.py
@@ -1,7 +1,7 @@
 
 
 def foo(n):
-    if (n > 10):
+    if (not (n > 10)):
         return (n + 10)
-    return (n - 5)
+    return (n - 6)
 

job ID 2:Outcome.KILLED:main
command: cosmic-ray worker main ['number_replacer', 'mutate_binary_operator'] [1, 0] nose -- tests.py
Traceback (most recent call last):
  File "/tmp/test/tests.py", line 12, in test_11_should_return_21
    self.assertEqual(main.foo(11), 21)
AssertionError: 0 != 21

--- mutation diff ---
--- a/tmp/test/main.py
+++ b/tmp/test/main.py
@@ -2,6 +2,6 @@
 
 def foo(n):
     if (n > 10):
-        return (n + 10)
+        return (n - 11)
     return (n - 5)
➜  test cosmic-ray report example.json --full-report                                               
job ID 1:Outcome.KILLED:main
command: cosmic-ray worker main ['number_replacer', 'add_not'] [2, 0] nose -- tests.py

....

--- mutation diff ---
--- a/tmp/test/main.py
+++ b/tmp/test/main.py
@@ -1,7 +1,7 @@
 
 
 def foo(n):
-    if (n > 10):
+    if (not (n > 10)):
         return (n + 10)
-    return (n - 5)
+    return (n - 6)
 

job ID 2:Outcome.KILLED:main
command: cosmic-ray worker main ['number_replacer', 'mutate_binary_operator'] [1, 0] nose -- tests.py
....
--- mutation diff ---
--- a/tmp/test/main.py
+++ b/tmp/test/main.py
@@ -2,6 +2,6 @@
 
 def foo(n):
     if (n > 10):
-        return (n + 10)
+        return (n - 11)
     return (n - 5)
```

It can now generate last2first algorithm to produce second order mutant.

**Comment by abingham** [comment]
I took a look at the work you did. If I understand it correctly, you're generating higher-order mutants by simply applying two consecutive mutations at the same time. I'm entirely in favor of supporting this kind of behavior, but I'd want to think very hard about how to best implement it. There seem to be a few implementation issues we need to consider.

First, as you mentioned in your initial message, we need to create some notion of a "mutation strategy". At a high level, it would determine the different sets of mutations that would be used in a session. I think this in itself isn't too complex. We've already go two strategies as examples: CR's current "single mutation" approach, and your "adjacent pairs" approach. Ultimately, I think a strategy could specify an arbitrary number of mutations for a given test run, and it would be up to the strategy implementors to ensure that the mutation selection makes sense.

The choice of mutations provided by the mutation strategy would be stored in the work-database (as it currently is), effectively separating the phases of a) mutation selection and b) mutation application/testing.

The second main issue I can see right now is how we store and communicate the mutation selections. First, we'd need to update the work-database to be able to store a set of mutations per run rather than a single one. This should not be difficult. Second, we'd need to be able to supply these mutation sets to the worker process. 

Currently we supply the worker with all of its parameters via the command line, and we could try extending that. Or we could consider using a configuration file from which the worker reads its parameters. (The main downside to this approach is that it would mean that workers would need to run in an environment where we could read and write files, implying both the existence of a filesystem and the correct permissions). Or perhaps worker processes could open a socket from which to read their configuration...that's a very interesting possibility, but also one with other implications.

Finally, we'd need to update the celery executor so that it could pass mutation sets instead of a single mutation. This should not be difficult at all.

Once we sort out these issues, the actual mutation and testing phases aren't substantially different from what we've already got. Your prototype demonstrates this nicely!

I suppose that higher-order mutation does introduce a new potential failure mode, however. In principle, the application of one mutation could alter the AST such that subsequent mutations could not be applied. We'd have to think about how this fits into our execution and reporting system. I think we would want to call this a failure of the mutation strategy, though perhaps I'm wrong in that assessment.

All in all, this is a very interesting topic, and I'm enthusiastic about adding support for it to CR!
