### ISSUE TITLE
cosmic-ray exec requires configured RabbitMQ/Celery

### ISSUE THREAD

**Issue by tomato42** [sixty-north/cosmic-ray#201]
When I initialise cosmic-ray using
```
cosmic-ray init --baseline 10 test_session tlsfuzzer -- tests
```
and then run it with
```
cosmic-ray exec test_session
```

I get an exception:
```
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/cosmic_ray/commands/execute.py", line 21, in execute
    job_id, command, (result_type, result_data) = r.get()
AttributeError: 'str' object has no attribute 'get'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/cosmic-ray", line 9, in <module>
    load_entry_point('cosmic-ray==1.0.0a1', 'console_scripts', 'cosmic-ray')()
  File "/usr/lib/python3.5/site-packages/cosmic_ray/cli.py", line 365, in main
    sys.exit(handler(sub_config))
  File "/usr/lib/python3.5/site-packages/cosmic_ray/cli.py", line 171, in handle_exec
    cosmic_ray.commands.execute(db)
  File "/usr/lib/python3.5/site-packages/cosmic_ray/commands/execute.py", line 25, in execute
    cosmic_ray.tasks.celery.app.control.purge()
  File "/usr/lib/python3.5/site-packages/celery/app/control.py", line 178, in purge
    return self.app.amqp.TaskConsumer(conn).purge()
  File "/usr/lib/python3.5/site-packages/celery/app/amqp.py", line 302, in TaskConsumer
    **kw
  File "/usr/lib/python3.5/site-packages/kombu/messaging.py", line 386, in __init__
    self.revive(self.channel)
  File "/usr/lib/python3.5/site-packages/kombu/messaging.py", line 399, in revive
    channel = self.channel = maybe_channel(channel)
  File "/usr/lib/python3.5/site-packages/kombu/connection.py", line 973, in maybe_channel
    return channel.default_channel
  File "/usr/lib/python3.5/site-packages/kombu/connection.py", line 819, in default_channel
    self.connection
  File "/usr/lib/python3.5/site-packages/kombu/connection.py", line 802, in connection
    self._connection = self._establish_connection()
  File "/usr/lib/python3.5/site-packages/kombu/connection.py", line 757, in _establish_connection
    conn = self.transport.establish_connection()
  File "/usr/lib/python3.5/site-packages/kombu/transport/pyamqp.py", line 130, in establish_connection
    conn.connect()
  File "/usr/lib/python3.5/site-packages/amqp/connection.py", line 294, in connect
    self.transport.connect()
  File "/usr/lib/python3.5/site-packages/amqp/transport.py", line 120, in connect
    self._connect(self.host, self.port, self.connect_timeout)
  File "/usr/lib/python3.5/site-packages/amqp/transport.py", line 161, in _connect
    self.sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
```

**Comment by abingham** [comment]
Which version (git sha) are you using? If you don't pass "--dist" to exec in the most recent version, then it shouldn't be trying to use celery. It may be that I haven't complete disabled celery in the local case, however; #192 should address that more fully.

**Comment by tomato42** [comment]
I tried both pip with `--pre` and setup.py install from current master

**Comment by abingham** [comment]
I'm not sure what's going on then. I just tried running a session on my machine without rabbit running, and I didn't run into any problems. Could you try testing from a fresh install of CR into a new virtualenv? It's possible that you're seeing an old installed version or something.

**Comment by tomato42** [comment]
I think I have mixed up pip and pip3 for some dependencies, when I redone everything on clean system, it worked without complaining about RabbitMQ.
