### ISSUE TITLE
More graceful handling of Ctrl-C in cosmic-ray init

### ISSUE THREAD

**Issue by rob-smallshire** [sixty-north/cosmic-ray#273]
I changed by mind while running cosmic-ray init, because I hadn't yet installed the py.test test-runner plugin.  Pressing Ctrl-C gives a large stack-trace, rather than just quietly exiting.

```
$ cosmic-ray init cosmic-ray-pytest-local.conf session1
[?] Top-level module: asm68
Test runner
  (0) unittest
[?] Enter menu selection: ^CTraceback (most recent call last):
  File "/Users/rjs/.virtualenvs/asm68/bin/cosmic-ray", line 11, in <module>
    sys.exit(main())
  File "/Users/rjs/.virtualenvs/asm68/lib/python3.6/site-packages/cosmic_ray/cli.py", line 298, in main
    common_option_handler=common_option_handler)
  File "/Users/rjs/.virtualenvs/asm68/lib/python3.6/site-packages/docopt_subcommands/__init__.py", line 69, in main
    result = commands(argv)
  File "/Users/rjs/.virtualenvs/asm68/lib/python3.6/site-packages/docopt_subcommands/subcommands.py", line 134, in __call__
    return handler(config)
  File "/Users/rjs/.virtualenvs/asm68/lib/python3.6/site-packages/cosmic_ray/cli.py", line 96, in handle_init
    handle_new_config(args)
  File "/Users/rjs/.virtualenvs/asm68/lib/python3.6/site-packages/cosmic_ray/cli.py", line 69, in handle_new_config
    handle.write(cosmic_ray.commands.new_config())
  File "/Users/rjs/.virtualenvs/asm68/lib/python3.6/site-packages/cosmic_ray/commands/new_config.py", line 35, in new_config
    returns="desc")
  File "/Users/rjs/.virtualenvs/asm68/lib/python3.6/site-packages/qprompt.py", line 113, in show
    return show_menu(self.entries, **self._show_kwargs)
  File "/Users/rjs/.virtualenvs/asm68/lib/python3.6/site-packages/qprompt.py", line 267, in show_menu
    choice = ask(msg, vld=valid)
  File "/Users/rjs/.virtualenvs/asm68/lib/python3.6/site-packages/qprompt.py", line 189, in inner
    return func(*args, **kwargs)
  File "/Users/rjs/.virtualenvs/asm68/lib/python3.6/site-packages/qprompt.py", line 365, in ask
    ans = get_input(msg)
KeyboardInterrupt
```

**Comment by abingham** [comment]
Fixed by PR #284
