### ISSUE TITLE
TypeError: sequence item 0: expected str instance, tuple found when running cosmic-ray init

### ISSUE THREAD

**Issue by rob-smallshire** [sixty-north/cosmic-ray#276]
So, I managed to get `cosmic-ray init` to sorta run; at least it appears to be doing some work for a while. Then I get this:

```
$ cosmic-ray init cosmic-ray-pytest-local.conf session1
baseline failed
Traceback (most recent call last):
  File "/Users/rjs/.virtualenvs/asm68/bin/cosmic-ray", line 11, in <module>
    sys.exit(main())
  File "/Users/rjs/.virtualenvs/asm68/lib/python3.6/site-packages/cosmic_ray/cli.py", line 298, in main
    common_option_handler=common_option_handler)
  File "/Users/rjs/.virtualenvs/asm68/lib/python3.6/site-packages/docopt_subcommands/__init__.py", line 69, in main
    result = commands(argv)
  File "/Users/rjs/.virtualenvs/asm68/lib/python3.6/site-packages/docopt_subcommands/subcommands.py", line 134, in __call__
    return handler(config)
  File "/Users/rjs/.virtualenvs/asm68/lib/python3.6/site-packages/cosmic_ray/cli.py", line 58, in handle_baseline
    print(''.join(work_record.data))
TypeError: sequence item 0: expected str instance, tuple found
Traceback (most recent call last):
  File "/Users/rjs/.virtualenvs/asm68/bin/cosmic-ray", line 11, in <module>
    sys.exit(main())
  File "/Users/rjs/.virtualenvs/asm68/lib/python3.6/site-packages/cosmic_ray/cli.py", line 298, in main
    common_option_handler=common_option_handler)
  File "/Users/rjs/.virtualenvs/asm68/lib/python3.6/site-packages/docopt_subcommands/__init__.py", line 69, in main
    result = commands(argv)
  File "/Users/rjs/.virtualenvs/asm68/lib/python3.6/site-packages/docopt_subcommands/subcommands.py", line 134, in __call__
    return handler(config)
  File "/Users/rjs/.virtualenvs/asm68/lib/python3.6/site-packages/cosmic_ray/cli.py", line 112, in handle_init
    subprocess.check_call(command.split())
  File "/usr/local/var/pyenv/versions/3.6.2/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cosmic-ray', 'baseline', 'cosmic-ray-pytest-local.conf']' returned non-zero exit status 1.
```

My config file looks like this:

```
module: asm68

baseline: 10

exclude-modules:

test-runner:
  name: pytest
  args: tests

execution-engine:
  name: local
```

**Comment by abingham** [comment]
Can you point me to the project you're using this on?

**Comment by rob-smallshire** [comment]
This was when using Cosmic Ray on this project: https://github.com/rob-smallshire/asm68

**Comment by rob-smallshire** [comment]
I'm unable to reproduce this using the latest version of Cosmic Ray, so I'll close it.
