### ISSUE TITLE
Incompetent tests should not be considered to be killed

### ISSUE THREAD

**Issue by blueyed** [sixty-north/cosmic-ray#336]
I've tried to use pytest-testmon (which does not make much sense since code is not changed on disk), but it shows that incompetent test runs are considered to be killed:

```
job ID 6b26381999ab41909ac3c95db8acf77e:incompetent:covimerage.utils
command: cosmic-ray worker covimerage.utils add_not 0
Traceback (most recent call last):

  File "…/Vcs/cosmic-ray/cosmic_ray/testing/test_runner.py", line 78, in __call__
    test_result = self._run()

  File "…/Vcs/cosmic-ray/plugins/test-runners/pytest/cosmic_ray_pytest_runner/runner.py", line 65, in _run
    raise TestRunnerFailure('pytest exited non-zero', exit_code, output)

cosmic_ray.testing.test_runner.TestRunnerFailure: ('pytest exited non-zero', 5, '============================= test session starts ==============================\nplatform linux -- Python 3.6.3, pytest-3.3.1.dev14+g4d2f05e4.d20171129, py-1.5.2, pluggy-0.6.0 -- …/src/covimerage/.venv/bin/python\ncachedir: .cache\ntestmon=True, changed files: 0, skipping collection of 59 items, run variant: default\nrootdir: …/src/covimerage, inifile: setup.cfg\nplugins: testmon-0.9.6, pdb-0.2.0, mock-1.6.3, cov-2.5.1, annotate-1.0.1\ncollecting ... collected 0 items\n\n============================= 59 tests deselected ==============================\n======================== 59 deselected in 0.03 seconds =========================\n')

--- mutation diff ---
--- a…/src/covimerage/covimerage/utils.py
+++ b…/src/covimerage/covimerage/utils.py
@@ -6,7 +6,7 @@
 RE_NON_EXECED = re.compile('^\\s*("|\\\\|end|$)')
 
 def get_fname_and_fobj_and_str(fname_or_fobj):
-    if isinstance(fname_or_fobj, string_types):
+    if (not isinstance(fname_or_fobj, string_types)):
         return (fname_or_fobj, None, fname_or_fobj)
     try:
         fname = fname_or_fobj.name
```

Exit code 5 means that no tests were collected (since `--testmon` deselected everything (no changes)).

This is related / caused by 7ae2c34 apparently.

**Comment by abingham** [comment]
For the purposes of calculating survival rate, incompetent mutants are counted as killed. For generating larger reports (e.g. `create_report()`) it's fine to distinguish incompetent and killed mutants, but for calculating survival rate we only need to distinguish survivors and others.
