### ISSUE TITLE
Supplying wrong file as counts command argument gives cryptic error

### ISSUE THREAD

**Issue by rob-smallshire** [sixty-north/cosmic-ray#369]
If I inadvertently supply the wrong file as the argument to counts I get a stack trace. As a user, I never expect to see internal Cosmic Ray stack traces.

In this case I supplied the session database rather than the session configuration file.

We should beef up the exception handling in the command implementation to give better error reporting.

```
$ cosmic-ray counts local-session-1.json
Traceback (most recent call last):
  File "/Users/rjs/.virtualenvs/asm68/bin/cosmic-ray", line 11, in <module>
    load_entry_point('cosmic-ray', 'console_scripts', 'cosmic-ray')()
  File "/Users/rjs/dev/cosmic-ray/cosmic_ray/cli.py", line 363, in main
    exit_at_end=False)
  File "/Users/rjs/.virtualenvs/asm68/lib/python3.6/site-packages/docopt_subcommands/__init__.py", line 69, in main
    result = commands(argv)
  File "/Users/rjs/.virtualenvs/asm68/lib/python3.6/site-packages/docopt_subcommands/subcommands.py", line 147, in __call__
    return handler(config)
  File "/Users/rjs/dev/cosmic-ray/cosmic_ray/cli.py", line 212, in handle_counts
    cosmic_ray.modules.fixup_module_name(config['module']),
KeyError: 'module'
```

**Comment by abingham** [comment]
I've started some work in the [`rework-config` branch](https://github.com/sixty-north/cosmic-ray/tree/rework-config) that should address some of these problems. The basic strategy is that, rather than a simple dict, we'll have a `Config` object that throws a `ConfigError` when you try to access something that doesn't exist. We can catch ConfigErrors and do something useful with them.

Also, if/when we move from a json database to something more industrial-strength (e.g. sqlite), I think we'll be less likely to have the specific issue you're seeing here.
