### ISSUE TITLE
TypeError: Object of type 'JSONDecodeError' is not JSON serializable

### ISSUE THREAD

**Issue by MartinThoma** [sixty-north/cosmic-ray#395]
## What I did

I tried to run cosmic-ray on https://github.com/MartinThoma/mpu/tree/cosmicray

## What happened

```
$ cosmic-ray exec cr_session
Traceback (most recent call last):
  File "/home/moose/.local/bin/cosmic-ray", line 11, in <module>
    sys.exit(main())
  File "/home/moose/.local/lib/python3.6/site-packages/cosmic_ray/cli.py", line 363, in main
    exit_at_end=False)
  File "/home/moose/.local/lib/python3.6/site-packages/docopt_subcommands/__init__.py", line 69, in main
    result = commands(argv)
  File "/home/moose/.local/lib/python3.6/site-packages/docopt_subcommands/subcommands.py", line 147, in __call__
    return handler(config)
  File "/home/moose/.local/lib/python3.6/site-packages/cosmic_ray/cli.py", line 178, in handle_exec
    cosmic_ray.commands.execute(session_file)
  File "/home/moose/.local/lib/python3.6/site-packages/cosmic_ray/progress.py", line 97, in wrapper
    return func(*args, **kwargs)
  File "/home/moose/.local/lib/python3.6/site-packages/cosmic_ray/commands/execute.py", line 48, in execute
    work_db.update_work_item(work_item)
  File "/home/moose/.local/lib/python3.6/site-packages/cosmic_ray/work_db.py", line 158, in update_work_item
    tinydb.Query().job_id == work_item.job_id)
  File "/home/moose/.local/lib/python3.6/site-packages/tinydb/database.py", line 513, in update
    cond, doc_ids
  File "/home/moose/.local/lib/python3.6/site-packages/tinydb/database.py", line 359, in process_elements
    self._write(data)
  File "/home/moose/.local/lib/python3.6/site-packages/tinydb/database.py", line 405, in _write
    self._storage.write(values)
  File "/home/moose/.local/lib/python3.6/site-packages/tinydb/database.py", line 111, in write
    self._storage.write(raw_data)
  File "/home/moose/.local/lib/python3.6/site-packages/tinydb/storages.py", line 110, in write
    serialized = json.dumps(data, **self.kwargs)
  File "/usr/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'JSONDecodeError' is not JSON serializable

```

**Comment by MartinThoma** [comment]
It seems to come from the following test case:

```

    def test_text_input(self):
        try:
            from io import StringIO
        except ImportError:
            from StringIO import StringIO
        import sys
        sys.stdin = StringIO(u"foo\nbar")
        text_input('foo')

```

**Comment by abingham** [comment]
Interesting! I would not be surprised if messing around with stdin like
that breaks CR in new an interesting ways. I'm installing you stuff now, so
I'll have a look at it.

**Comment by abingham** [comment]
I was able to run the tests in `test_shell.py` over all of the mutants, and it didn't crash. I would guess that the problem lies somewhere else.

What version of CR are you using? The JSONDecodeError has historically meant that something besides valid JSON was showing up on the worker subprocess's stdout, but recent versions of CR should fix that. Perhaps this means I need to push a new version to PyPI...

**Comment by abingham** [comment]
I've pushed 3.2.0 to PyPI, and this might very well address the problem you're seeing. Let me know how it goes.

**Comment by MartinThoma** [comment]
After updating to 3.2.0 (and a couple of other changes), I get

```
Traceback (most recent call last):
  File "/home/moose/.local/bin/cosmic-ray", line 11, in <module>
    sys.exit(main())
  File "/home/moose/.local/lib/python3.6/site-packages/cosmic_ray/cli.py", line 357, in main
    exit_at_end=False)
  File "/home/moose/.local/lib/python3.6/site-packages/docopt_subcommands/__init__.py", line 69, in main
    result = commands(argv)
  File "/home/moose/.local/lib/python3.6/site-packages/docopt_subcommands/subcommands.py", line 147, in __call__
    return handler(config)
  File "/home/moose/.local/lib/python3.6/site-packages/cosmic_ray/cli.py", line 64, in handle_baseline
    print(''.join(work_item.data))
TypeError: sequence item 0: expected str instance, tuple found
Error in subprocess
Command '['cosmic-ray', 'baseline', 'cr-config.yaml']' returned non-zero exit status 1.
```
