### ISSUE TITLE
Doctest support

### ISSUE THREAD

**Issue by MartinThoma** [sixty-north/cosmic-ray#396]
Usually, I use pytest when I want to execute doctests (see https://github.com/MartinThoma/mpu/tree/cosmicray ). But configuring the test-runner `pytest` does not work for https://github.com/MartinThoma/mpu/blob/cosmicray/cr-config.yaml

```
    cosmic-ray init cr-config.yaml cr_session && cosmic-ray exec cr_session
    baseline failed
    Traceback (most recent call last):
      File "/home/moose/.local/bin/cosmic-ray", line 11, in <module>
        sys.exit(main())
      File "/home/moose/.local/lib/python3.6/site-packages/cosmic_ray/cli.py", line 357, in main
        exit_at_end=False)
      File "/home/moose/.local/lib/python3.6/site-packages/docopt_subcommands/__init__.py", line 69, in main
        result = commands(argv)
      File "/home/moose/.local/lib/python3.6/site-packages/docopt_subcommands/subcommands.py", line 147, in __call__
        return handler(config)
      File "/home/moose/.local/lib/python3.6/site-packages/cosmic_ray/cli.py", line 64, in handle_baseline
        print(''.join(work_item.data))
    TypeError: sequence item 0: expected str instance, tuple found
    Error in subprocess
    Command '['cosmic-ray', 'baseline', 'cr-config.yaml']' returned non-zero exit status 1.
    Makefile:13: recipe for target 'mutation-test' failed
    make: *** [mutation-test] Error 1
```

When I execute pytest directly or with tox, it works.

**Comment by abingham** [comment]
This looks like a confluence of two problems. First, the dump is telling me
that "baseline failed". This generally means that the init phase was
running a baseline timing (i.e. timing your test suite on unmutated code),
and that test run returned a non-0 value. Normally this means that the test
suite failed, and CR currently assumes that any further testing would be
meaningless.

The second issue is that we're clearly not reporting that issue very well.

I'll try to look into this tomorrow if I have some time. My first
suggestion, though, is to see if your testsuite is actually passing and
exiting with 0.
