### ISSUE TITLE
Windows 10 and CR

### ISSUE THREAD

**Issue by LLKoder** [sixty-north/cosmic-ray#431]
When I try to run Cosmic-Ray I get an error. I use example_project script.

It's what I did.

X:\...\Python>cd example_project

X:\...\Python\example_project>cosmic-ray -v INFO init cosmic-ray.unittest.local.conf example-session.sqlite
2019-05-09 10:06:07,536 root INFO Reading config from 'cosmic-ray.unittest.local.conf'
2019-05-09 10:06:07,544 root INFO Modules discovered: [WindowsPath('adam/__init__.py'), WindowsPath('adam/adam_1.py'), WindowsPath('adam/adam_2.py'), WindowsPath('adam/cli.py')]
2019-05-09 10:06:12,419 root INFO spor skipping be31a2aa58e4446bac5b80082d312569 core/ReplaceComparisonOperator_Eq_NotEq 0 adam\cli.py (2, 12) (2, 14)
2019-05-09 10:06:12,689 root INFO spor skipping c59b53ac8e97499b8d44b20be64ffdd8 core/ReplaceComparisonOperator_Eq_Lt 0 adam\cli.py (2, 12) (2, 14)
2019-05-09 10:06:12,713 root INFO spor skipping 259a894a59b24821b4679893d9dfc304 core/ReplaceComparisonOperator_Eq_LtE 0 adam\cli.py (2, 12) (2, 14)
2019-05-09 10:06:12,753 root INFO spor skipping 8fc724f9d63e431c945316e41bdf1dbc core/ReplaceComparisonOperator_Eq_Gt 0 adam\cli.py (2, 12) (2, 14)
2019-05-09 10:06:12,777 root INFO spor skipping 8c6f4058d1bd484c85dd49203b313fc4 core/ReplaceComparisonOperator_Eq_GtE 0 adam\cli.py (2, 12) (2, 14)
2019-05-09 10:06:12,834 root INFO spor skipping da12b8f91e6740fcb496290a2c9e6b4d core/ReplaceComparisonOperator_Eq_Is 0 adam\cli.py (2, 12) (2, 14)
2019-05-09 10:06:12,894 root INFO spor skipping 0447038f82a44e92ae5f5c33fb8a18bf core/ReplaceComparisonOperator_Eq_IsNot 0 adam\cli.py (2, 12) (2, 14)
2019-05-09 10:06:12,924 root INFO spor skipping 27ff8d7d35cb43e0bce2d3aa9697eb69 core/AddNot 0 adam\cli.py (2, 3) (2, 25)
2019-05-09 10:06:12,955 root INFO spor skipping 3430fffe913048dab15102a8c223b8d2 core/NumberReplacer 0 adam\cli.py (3, 8) (3, 9)
2019-05-09 10:06:12,977 root INFO spor skipping c18da7580a744755ab6310d336e1cb66 core/NumberReplacer 1 adam\cli.py (3, 8) (3, 9)

X:\...\Python\example_project>cosmic-ray -v INFO exec example-session.sqlite
2019-05-09 10:06:30,646 cosmic_ray.commands.execute INFO Beginning execution
Process SpawnPoolWorker-2:
Process SpawnPoolWorker-1:
Traceback (most recent call last):
  File "c:\users\...\appdata\local\programs\python\python37-32\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "c:\users\...\appdata\local\programs\python\python37-32\lib\multiprocessing\process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\...\appdata\local\programs\python\python37-32\lib\multiprocessing\pool.py", line 105, in worker
    initializer(*initargs)
  File "c:\users\...\appdata\local\programs\python\python37-32\lib\site-packages\cosmic_ray\execution\local.py", line 65, in _initialize_worker
    _workspace = ClonedWorkspace(config.cloning_config)
  File "c:\users\...\appdata\local\programs\python\python37-32\lib\site-packages\cosmic_ray\cloning.py", line 72, in __init__
    _build_env(self._venv_path)
  File "c:\users\...\appdata\local\programs\python\python37-32\lib\site-packages\cosmic_ray\cloning.py", line 159, in _build_env
    check=True)
  File "c:\users\...\appdata\local\programs\python\python37-32\lib\subprocess.py", line 472, in run
    with Popen(*popenargs, **kwargs) as process:
  File "c:\users\...\appdata\local\programs\python\python37-32\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "c:\users\...\appdata\local\programs\python\python37-32\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
Traceback (most recent call last):
  File "c:\users\...\appdata\local\programs\python\python37-32\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "c:\users\...\appdata\local\programs\python\python37-32\lib\multiprocessing\process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\...\appdata\local\programs\python\python37-32\lib\multiprocessing\pool.py", line 105, in worker
    initializer(*initargs)
  File "c:\users\...\appdata\local\programs\python\python37-32\lib\site-packages\cosmic_ray\execution\local.py", line 65, in _initialize_worker
    _workspace = ClonedWorkspace(config.cloning_config)
  File "c:\users\...\appdata\local\programs\python\python37-32\lib\site-packages\cosmic_ray\cloning.py", line 72, in __init__
    _build_env(self._venv_path)
  File "c:\users\...\appdata\local\programs\python\python37-32\lib\site-packages\cosmic_ray\cloning.py", line 159, in _build_env
    check=True)
  File "c:\users\...\appdata\local\programs\python\python37-32\lib\subprocess.py", line 472, in run
    with Popen(*popenargs, **kwargs) as process:
  File "c:\users\...\appdata\local\programs\python\python37-32\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "c:\users\...\appdata\local\programs\python\python37-32\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
Process SpawnPoolWorker-3:
^C

I had a problem with Git path before, I decided this question. Just I had no path in environment variables. Maybe that helps.

Windows 10
Git 2.21.0.windows.1
Python 3.7.3
Cosmic ray 5.2.0

PyCharm 2019.1.1 (Community Edition)
Build #PC-191.6605.12, built on April 3, 2019
JRE: 11.0.2+9-b159.34 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by abingham** [comment]
The problem is almost certainly that CR doesn't work on correctly on windows. In some of the new workspace cloning code (where we create virtual environments for test run isolation) we are using 'bin' to find the python executable. On windows, of course, that should be "scripts", and I'm pretty sure this is the cause of the problem you're seeing.

So...I'll look into this and hopefully have something for you soon.

**Comment by abingham** [comment]
I think the master branch should fix this problem now. Can you give it a try?

There might still be problems, but I'd like to see how it works for you.

**Comment by LLKoder** [comment]
As I said before, I'm beginner, I execute the wheeled package from PyPI before. And now I cannot find the executed file (cosmic-ray) in that branch. Can you say me how I can execute CR from the branch?
I already cloned the branch to myself.

**Comment by LLKoder** [comment]
I have run that branch, now I'm testing...

**Comment by LLKoder** [comment]
Good... it's working. Thanks.
Can close this issue as solved? Just I see other opened issues and see no one closed issue.
Also, I found another problem. I'll write to you by email, maybe it'll be another opened issue or maybe not.

**Comment by abingham** [comment]
> Can close this issue as solved?

Yes, if it works for you. 

> Just I see other opened issues and see no one closed issue.

The default github issue view only shows open issues. You have to click on the "closed issues" label (or modify the text filter) to see the closed ones.

> Also, I found another problem. I'll write to you by email, maybe it'll be another opened issue or maybe not.

I will almost certainly ask you to create a new issue. They are the best way for me to handle stuff related to cosmic ray.

**Comment by LLKoder** [comment]
Thanks again. :)

**Comment by abingham** [comment]
Thanks for reporting these issues. I'll do my best to keep things working for you.
